networks:
  web:
    external: true
services:
  webapp:
    # Der Image-Name wird durch die GitLab CI/CD Pipeline gesetzt
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
    container_name: ${$PRODUCTION_URL}-portfolio
    restart: unless-stopped
    networks:
      - web