server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Anfragen für Routen an die index.html weiterleiten
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Statische Dateien mit langem Cache versehen
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}